spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/myjava
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect